ex_trackerapp/urls.py
from django.urls import path
from .views import *



app_name="ex_trackerapp"
urlpatterns=[
    path('',ClientExpenditureList.as_view(),name='clientexlist'),	
	path("expenditure/",ClientExpenditureView.as_view(),name='clientexpenditure'),
	path("client/expn-<int:pk>/detail/",ClientExpenDetailView.as_view(),name='clientexpendetail'),

	path('pie-chart/',pie_chart, name='pie-chart'),
	path('barhome/',home, name='home'),
    path('expenditure-chart/',expenditure_chart, name='expenditure-chart'),
    

    path('clientexpenselist2/',ClientExpenditureList2.as_view(),name='clientexlist2'),
	path("client/expn-<int:pk>/detail2/",ClientExpenDetailView2.as_view(),name='clientexpendetail2'),

	path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", SignupView.as_view(), name="signup"),
    path("ajax_check_useremail/", AjaxCheckUseremailView.as_view(),name='ajaxcheckuseremail'),

	path("self-expenditure/",ClientSelfExpenditureView.as_view(),name='clientselfexpenditure'),
	path("self-expenditure2/",ClientSelfExpenditureView2.as_view(),name='clientselfexpenditure2'),
	








	]

ex_trackerproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('maddy5-admin/', admin.site.urls),
    path("",include("ex_trackerapp.urls")),
]



urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ex_trackerapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User




class ExpenditureForm(forms.ModelForm):
	class Meta:
		model=CustomerExpenditure
		fields=['food','education','cloths','vehicle','extra','saving','status']
		widgets={
		'food': forms.NumberInput(attrs={
                "class": "form-control",
                'placeholder':'Enter food amount...'
            }),
		'education': forms.NumberInput(attrs={
                "class": "form-control",
                'placeholder':'Enter education amount...'
            }),
		'cloths': forms.NumberInput(attrs={
                "class": "form-control",
                'placeholder':'Enter cloths amount...'
            }),
		'vehicle': forms.NumberInput(attrs={
                "class": "form-control",
                'placeholder':'Enter vehicle amount...'
            }),
		'extra': forms.NumberInput(attrs={
                "class": "form-control",
                'placeholder':'Enter extra amount...'
            }),
		'saving': forms.NumberInput(attrs={
                "class": "form-control",
                'placeholder':'Enter saving amount...'
            }),
		'status': forms.Select(attrs={
                "class": "form-control",
               
            }),
		}



class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control",
        "autocomplete": "off",
        "placeholder": "Enter Email"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "form-control",
        "autocomplete": "off",
        "placeholder": "Enter password"
    }))




class SignupForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Username"
		}))
	email=forms.EmailField(widget=forms.EmailInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter email"
		}))
	password=forms.CharField(widget=forms.PasswordInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Password"
		}))
	confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Password"
		}))


	def clean_username(self):
		uname=self.cleaned_data['username']
		if User.objects.filter(username=uname).exists():
			raise forms.ValidationError("Username is already exist")

		
		return uname



	def clean_confirm_password(self):
		pw=self.cleaned_data['password']
		c_pw=self.cleaned_data['confirm_password']
		if (pw !=c_pw):
			raise forms.ValidationError("Password did not match.")

		if (len(pw)<6):
			raise forms.ValidationError("Password too short")

		numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
		c = 0
		for i in c_pw:
			if i in numbers:
				c += 1
		if c < 1:
			raise forms.ValidationError("must include a number")


		return c_pw



class CategoryForm(forms.ModelForm):
	class Meta:
		model=Category
		fields=['name']




class SubjectForm(forms.ModelForm):
	class Meta:
		model=Subject
		fields=['category','title_name','amount']

	def __init__(self, user, *args, **kwargs):
		super(SubjectForm, self).__init__(*args, **kwargs)
		self.fields['category'].queryset = Category.objects.filter(person=user)

templates/clienttemplates/clientbarhome.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}

  <div id="container" style="width: 75%;">
    <canvas id="expenditure-chart" data-url="{% url 'ex_trackerapp:expenditure-chart' %}"></canvas>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    $(function () {

      var $expenditureChart = $("#expenditure-chart");
      $.ajax({
        url: $expenditureChart.data("url"),
        success: function (data) {

          var ctx = $expenditureChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Total expenditure',
                backgroundColor: [
        '#0000ff', '#ff0000', '#ffff00', '#008000', '#4b0082','#650d19'
        ],
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Expenditure Bar Chart'
              }
            }
          });

        }
      });

    });

  </script>

{% endblock %}

templates/clienttemplates/clientbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
</head>
<body>
	<div class="topnav" id="myTopnav">
		<div class="container">
			<a href="{% url 'ex_trackerapp:clientexlist' %}" class="active">Home</a>
			<a href="{% url 'ex_trackerapp:clientexpenditure' %}">Expenditure</a>
			<a href="{% url 'ex_trackerapp:clientexlist2' %}">BarCharts</a>
			<a href="{% url 'ex_trackerapp:clientselfexpenditure' %}">Create</a>
			<a href="{% url 'ex_trackerapp:pie-chart' %}">Pie Visual</a>
			<a href="{% url 'ex_trackerapp:home' %}">BarVisualize</a>
			
			{% if request.user.is_authenticated %}
			<a href="#">{{request.user}}</a>
			<a href="{% url 'ex_trackerapp:logout' %}" >Logout</a>
			{% endif %}


		</div>
	</div>

	<hr>
	{% block content %}
	{% endblock %}

</body>
</html>

templates/clienttemplates/clientdatavisual.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}
  <div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3','#808080'
          ],
          
        }],
        labels: {{ labels|safe }}
     
      options: {
        responsive: true
      }
 

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>


{% endblock %}

templates/clienttemplates/clienterrorpage.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h3>Page not found !!!</h3>

</body>
</html>

templates/clienttemplates/clientexpendetail.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}
<div class="row" style="background-color:#B0C4DE">
	<div class="col-md-2">
		
	</div>
	<div class="col-md-10">
		<div id="container" style="width: 75%;">
			<canvas id="pie-chart"></canvas>
		</div>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

	var config = {
		type: 'pie',
		data: {
			datasets: [{
				data: {{ data|safe }},
				backgroundColor: [
				'#0000ff', '#ff0000', '#ffff00', '#008000', '#4b0082','#650d19'
				],
				label:''
			}],
			labels: {{ labels|safe }}
		},
		options: {
			responsive: true,
			legend: {
				position: 'top',
			},
		}
	};

	window.onload = function() {
		var ctx = document.getElementById('pie-chart').getContext('2d');
		window.myPie = new Chart(ctx, config);
	};

</script>

{% endblock %}

templates/clienttemplates/clientexpendetail2.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}
<div class="row">
  <div class="col-md-2">
    
  </div>
  <div class="col-md-10">
    <div id="container" style="width: 75%;">
      <canvas id="bar-chart"></canvas>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

  var config = {
    type: 'bar',
    data: {
      datasets: [{
        data: {{ data|safe }},
        backgroundColor: [
        '#0000ff', '#ff0000', '#ffff00', '#008000', '#4b0082','#650d19'
        ],
        label:'All Expenditures'
      }],
      labels: {{ labels|safe }}
    },
    options: {
      responsive: true,
      
      
    }
  };

  window.onload = function() {
    var ctx = document.getElementById('bar-chart').getContext('2d');
    window.myPie = new Chart(ctx, config);
  };

</script>

{% endblock %}

templates/clienttemplates/clientexpenditure.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}



{% block content %}
<div class="row" style="background-color: #8ae6d4">
	<div class="col-md-3 mx-auto" style="background-color:#49b927">
		<div class="content-fluid">
			<h4 class="text text-center"><u>Expenditure Form</u></h4>
			<form method="post">
				<style type="text/css">
                              input[type=number]::-webkit-inner-spin-button, 
                              input[type=number]::-webkit-outer-spin-button { 
                                -webkit-appearance: none; 
                                margin: 0; 
                              }
                           </style>
				{% csrf_token %}<br>

				{{form.food}}<br>

				{{form.education}}<br>

				{{form.cloths}}<br>

				{{form.vehicle}}<br>

				{{form.extra}}<br>

				{{form.saving}}<br>

				{{form.status}}<br>

				<button class="btn btn-danger">Submit</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/clientbase.html' %}


{% block content %}
<div class="container" style="background-color:#D3D3D3" >
	<div class="row">
		<div class="col-md-1">

		</div>
		<div class="col-md-11">
			<h4 class="text text-center">All Expenditure List</h4><br>
			<table class="table table-bordered table-hover table-sm">
				<thead>
					<tr>
						<th>S.N</th>
						<th>Food</th>
						<th>Education</th>
						<th>Cloths</th>
						<th>Vehicle</th>
						<th>Extra</th>
						<th>Saving</th>
						<th>Status</th>
						<th>Date</th>
					</tr>
				</thead>
				<tbody>
					{% for expn in request.user.customerexpenditure_set.all %}
					<tr>	
						<td>{{forloop.counter}}</td>
						<td>{{expn.food}}</td>
						<td>{{expn.education}}</td>
						<td>{{expn.cloths}}</td>
						<td>{{expn.vehicle}}</td>
						<td>{{expn.extra}}</td>
						<td>{{expn.saving}}</td>
						<td>{{expn.status}}</td>
						<td><a href="{% url 'ex_trackerapp:clientexpendetail' expn.id %}">{{expn.created_at}}</a></td>
					</tr>
					{% endfor %}
				</tbody>
				
			</table>

		</div>
	</div>
</div>
{% endblock %}

templates/clienttemplates/clienthome2.html
{% extends 'clienttemplates/clientbase.html' %}


{% block content %}
<div class="container" style="background-color:#D3D3D3" >
	<div class="row">
		<div class="col-md-1">

		</div>
		<div class="col-md-11">
			<h4 class="text text-center">All Expenditure List</h4><br>
			<table class="table table-bordered table-hover table-sm">
				<thead>
					<tr>
						<th>S.N</th>
						<th>Food</th>
						<th>Education</th>
						<th>Cloths</th>
						<th>Vehicle</th>
						<th>Extra</th>
						<th>Saving</th>
						<th>Status</th>
						<th>Date</th>
					</tr>
				</thead>
				<tbody>
					{% for expn in request.user.customerexpenditure_set.all %}
					<tr>	
						<td>{{forloop.counter}}</td>
						<td>{{expn.food}}</td>
						<td>{{expn.education}}</td>
						<td>{{expn.cloths}}</td>
						<td>{{expn.vehicle}}</td>
						<td>{{expn.extra}}</td>
						<td>{{expn.saving}}</td>
						<td>{{expn.status}}</td>
						<td><a href="{% url 'ex_trackerapp:clientexpendetail2' expn.id %}">{{expn.created_at}}</a></td>
					</tr>
					{% endfor %}
				</tbody>
				
			</table>

		</div>
	</div>
</div>
{% endblock %}

templates/clienttemplates/clientpie_chart.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}
<div id="container" style="width: 75%;">
  <canvas id="pie-chart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

  var config = {
    type: 'pie',
    data: {
      datasets: [{
        data: {{ data|safe }},
        backgroundColor: [
        '#0000ff', '#ff0000', '#ffff00', '#008000', '#4b0082'
        ],
        label: 'Expenditure'
      }],
      labels: {{ labels|safe }}
    },
    options: {
      responsive: true
    }
  };

  window.onload = function() {
    var ctx = document.getElementById('pie-chart').getContext('2d');
    window.myPie = new Chart(ctx, config);
  };

</script>

{% endblock %}

templates/clienttemplates/clientselfexpenditurecategory.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}



{% block content %}
<br>

<div class="row" style="background-color: #8ae6d4">
	<div class="col-md-3 mx-auto" style="background-color:#49b927">
		<div class="content-fluid">
			<h4 class="text text-center"><u>Subject Create Form</u></h4>
			<form method="post">
				<style type="text/css">
                              input[type=number]::-webkit-inner-spin-button, 
                              input[type=number]::-webkit-outer-spin-button { 
                                -webkit-appearance: none; 
                                margin: 0; 
                              }
                           </style>
				
				{% csrf_token %}

				{{form.as_p}}<br>

				<button class="btn btn-danger">Submit</button> 
			</form>
			<br><a href="{% url 'ex_trackerapp:clientselfexpenditure2' %}"><button class="btn btn-danger">Create New Category</button></a>
		</div>
	</div>
</div>

{% endblock %}

templates/clienttemplates/clientselfexpenditurecategory2.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}



{% block content %}
<br>

<div class="row" style="background-color: #8ae6d4">
	<div class="col-md-3 mx-auto" style="background-color:#49b927">
		<div class="content-fluid">
			<h4 class="text text-center"><u>Category Create Form</u></h4>
			<form method="post">
				
				{% csrf_token %}

				{{def.as_p}}<br>

				<button class="btn btn-danger">Submit</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/clienttemplates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	
	<div class="login-box">
		<h1>Login Form</h1>
		<form method="POST">
			{% csrf_token %}
			<div class="textbox">
			{{form.email}}
			<br><br>
			{{form.password}}
			</div>
			<button class="btn btn-info">Submit</button>
			<span class="text-danger">
				{{error}}
			</span>	
		</form>
		Don't have an account ? <a href="{% url 'ex_trackerapp:signup' %}">Signup</a>
	</div>

</body>
</html>

templates/clienttemplates/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	
<div class="login-box">
		<h1>Signup Form</h1>
		
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info" id="btn">Submit</button>
			<span class="text-danger">
				{{error}}
			</span>
			<p id="error" style="color:red"></p>
			
		</form>
		Already have an account ? <a href="{% url 'ex_trackerapp:login' %}">Login</a>
		
</div>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
  
  
<script >
$(document).ready(function(){
	$("#id_email").on("keyup",function(){
		var uemail=$(this).val();
		$.ajax({
			url:"/ajax_check_useremail/",
			data:{
				"email":uemail
			},
			success:function(data){
				
				if (data.message=="unavailable"){
					$("#error").text("Email is already exist.");
					$("#btn").attr("disabled","true")

				}
				else{
					$("#error").text("");
					$("#btn").removeAttr("disabled")



				}
			}
		})


	})
})	


</script>


</body>
</html>